## toml file below equals to the command 
## "docker run -d -v /go/src/gxd-cli:/code -w /code --net iot -p 8974:80 -p 8996:8080 alpine ./gin-server"
title = "TOML test"
[[services]]
 detach = false
 name = "tg" # container name
 image = "alpine" 
 work_dir = "/code"
 net = "iot" # container network
 cmd = "echo hello"
 auto_remove = true
 [[services.ports]]
  host = 8974
  target = 80
 [[services.ports]]
  host = 8996
  target = 8080

 [[services.volumes]]
  host = "pwd"
  target = "/code"

 [[services.volumes]]
  host = "pwd/tmp"
  target = "/cg"
 [[services]]
 name = "tb"
 image = "alpine"
 cmd = "echo hello world."