## toml file below equals to the command 
## "docker run -d -v /go/src/gxd-cli:/code -w /code --net iot -p 8974:80 -p 8996:8080 alpine ./gin-server"
title = "TOML test"
[service]
 detach = false
 name = "test" # container name
 image = "alpine" 
 work_dir = "/code"
 net = "iot" # container network
 cmd = "./gin-server"
 [[service.ports]]
  host = 8974
  target = 80
 [[service.ports]]
  host = 8996
  target = 8080

 [[service.volumes]]
  host = "/go/src/gxd-cli/"
  target = "/code"
